apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users-api
          image: svestor/kube-aws-users:latest
          imagePullPolicy: Always
          env:
            - name: MONGODB_CONNECTION_URI
              value: 'mongodb+srv://svestor:supersecretpass@cluster0.a9myspe.mongodb.net/users?retryWrites=true&w=majority&appName=Cluster0'
            - name: AUTH_API_ADDRESSS
              value: 'auth-service.default:3000'
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "256m"
          ports:
          - containerPort: 3000

